parameters:
- name: image_type
  displayName: Build Agent Image
  type: string
  default: windows2019
  values:
  - windows2019
  - windows2022
  - ubuntu2004
  - ubuntu2204
- name: runner_images_version
  displayName: runner-images Version
  type: string
  default: release
  values:
  - alpha
  - prerelease
  - release
- name: variable_group
  displayName: Variable Group
  type: string
  default: BuildAgents
- name: agent_pool
  displayName: Agent Pool
  type: string
  default: 'Host Pool - Image'
- name: update_type
  displayName: 'Update vmss (VM Scale Set) or galleryvm (Gallery VM Image) ?'
  type: string
  default: galleryvm
  values:
  - galleryvm
  - vmss

trigger: none

stages:
- stage: InstallPwsh
  jobs:
  - job: InstallPowershell
    pool:
      name: ${{ parameters.agent_pool }}
    steps:
    - checkout: self
    - ${{ if in(parameters.image_type, 'ubuntu2004', 'ubuntu2204') }}:
      - script: |
          sudo apt-get update
          sudo apt-get install -y powershell
        displayName: Install PowerShell Core on Ubuntu
    - ${{ if in(parameters.image_type, 'windows2019', 'windows2022') }}:
      - powershell: |
          choco install powershell-core -y
        displayName: Install PowerShell Core on Windows

- template: buildagent-generation-template.yml
  parameters: 
    image_type: ${{ parameters.image_type }}
    runner_images_version: ${{ parameters.runner_images_version }}
    variable_group: ${{ parameters.variable_group }}
    agent_pool: ${{ parameters.agent_pool }}
    update_type: ${{ parameters.update_type }}